#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep 01 19:49:31 2020

@author: mdtamjidhossain
"""
import string

# cipherText = "lrvmnir bpr sumvbwvr jx bpr lmiwv yjeryrkbi jx qmbm wi bpr xjvni mkd ymibrut jx irhx wi bpr riirkvr jx ymbinlmtmipw utn qmumbr dj w ipmhh but bj rhnvwdmbr bpr yjeryrkbi jx bpr qmbm mvvjudwko bj yt wkbrusurbmbwjk lmird jk xjubt trmui jx ibndt wb wi kjb mk rmit bmiq bj rashmwk rmvp yjeryrkb mkd wbi iwokwxwvmkvr mkd ijyr ynib urymwk nkrashmwkrd bj ower m vjyshrbr rashmkmbwjk jkr cjnhd pmer bj lr fnmhwxwrd mkd wkiswurd bj invp mk rabrkb bpmb pr vjnhd urmvp bpr ibmbr jx rkhwopbrkrd ywkd vmsmlhr jx urvjokwgwko ijnkdhrii ijnkd mkd ipmsrhrii ipmsr w dj kjb drry ytirhx bpr xwkmh mnbpjuwbt lnb yt rasruwrkvr cwbp qmbm pmi hrxb kj djnlb bpmb bpr xjhhjcwko wi bpr sujsru msshwvmbwjk mkd wkbrusurbmbwjk w jxxru yt bprjuwri wk bpr pjsr bpmb bpr riirkvr jx jqwkmcmk qmumbr cwhh urymwk wkbmvb"
cipherText = "PHHW PH DIWHU WKH WRJD SDUWB"
KeyLength = 26

          
   
NUM = 31
   
def positions(str): 
    positionsList = []
    for i in str:
        positionsList.append((ord(i) & NUM))
    return positionsList       
   

cipherTextList = []
cipherTextList = cipherText.split(' ')

fullPositionList = []

for text in cipherTextList:
    str = text
    fullPositionList.append(positions(str))
    

fullpaliantextAlphabetList = [] 
word = ''  
wordList = []
for key in range(2,KeyLength):
    for wordPosition in fullPositionList:
        # print(wordPosition)
        for alphabetPosition in wordPosition:
            plaintextAlphabetPosition = (alphabetPosition - key) % 26
            alphabet=string.ascii_lowercase
            word = word + alphabet[plaintextAlphabetPosition]

        fullpaliantextAlphabetList.append(word)
        word = ''
    wordList.append(fullpaliantextAlphabetList)
    fullpaliantextAlphabetList =[]

sentence = ''
for i in wordList:
    for q in i:
        sentence = sentence+" "+q
    print(sentence+'\n')
    sentence = ''

    



